/**********************************************************************
 * The JeamLand talker system.
 * (c) Andy Fiddaman, 1993-97
 *
 * File:	cmd.table.c
 * Function:	The command table
 **********************************************************************/
#include <stdio.h>
#include <sys/types.h>
#include <netinet/in.h>
#include "jeamland.h"

#include "cmd.table.h"

#if defined(INETD_SUPPORT) || defined(CDUDP_SUPPORT)
extern void f_hosts(struct user *, int, char **);
#endif

/* The following comment is used by lexer, do not remove! */
/* CT */
struct command partial_commands[] = {
/* Visitor partial commands */
	{ "?",		f_help,		L_VISITOR,
	  CMD_PARTIAL,	0, NULL },
	{ "'",		f_say,		L_VISITOR,
	  CMD_PARTIAL,	1, "<text>" },
	{ "\"",		f_say,		L_VISITOR,
	  CMD_PARTIAL,	1, "<text>" },
	{ ":",		f_emote,	L_VISITOR,
	  CMD_PARTIAL,	1, "<text>" },
	{ ";",		f_emote,	L_VISITOR,
	  CMD_PARTIAL,	1, "<text>" },
	{ ">",		f_tell,		L_VISITOR,
	  CMD_PARTIAL,	2, "<user> <message>" },
	{ "<",		f_tell,		L_VISITOR,
	  CMD_PARTIAL,	2, "<user> <message>" },
	{ "-",		f_to,		L_VISITOR,
	  CMD_PARTIAL,	2, "<user> <message>" },
/* Resident partial commands */
	{ "=",		f_whisper,	L_RESIDENT,
	  CMD_PARTIAL,	2, "<user> <message>" },
	{ NULL, 	NULL, 		0,
	  0,		0, NULL },
	};

struct command commands[] = {
/* Visitor commands */
	{ "alconf",	f_alconf,	L_VISITOR,
	  0,		1, "<alias profile>" },
	{ "assist",	f_assist,	L_VISITOR,
	  0,		0, NULL },
	{ "attr",	f_attr,		L_VISITOR,
	  0,		0, NULL },
	{ "brief",	f_brief,	L_VISITOR,
	  0,		0, NULL },
	{ "clear",	f_clear,	L_VISITOR,
	  0,		0, NULL },
	{ "commands", 	f_commands, 	L_VISITOR,
	  0,		0, NULL },
	{ "converse",	f_converse,	L_VISITOR,
	  0,		0, NULL },
	{ "date",	f_date,		L_VISITOR,
	  0,		0, NULL },
	{ "echoback",	f_echoback,	L_VISITOR,
	  0,		0, NULL },
	{ "emote",	f_emote,	L_VISITOR,
	  0,		1, "<text>" },
	{ "exa",	f_examine,	L_VISITOR,
	  0,		1, "<object>" },
	{ "examine",	f_examine,	L_VISITOR,
	  0,		1, "<object>" },
	{ "feelings",	f_feelings,	L_VISITOR,
	  0,		0, NULL },
	{ "fixscreen",	f_fixscreen,	L_VISITOR,
	  0,		0, NULL },
#ifdef SUPER_SNOOP
	{ "harassment",	f_harassment,	L_VISITOR,
	  0,		1, "<user>" },
#endif
	{ "headers",	f_headers,	L_VISITOR,
	  0,		0, NULL },
	{ "help",	f_help,		L_VISITOR,
	  0,		0, NULL },
	{ "history",	f_history,	L_VISITOR,
	  0,		0, NULL },
	{ "idea",	f_dolog,	L_VISITOR,
	  0,		0, NULL },
	{ "l",		f_look,		L_VISITOR,
	  0,		0, NULL },
	{ "look",	f_look,		L_VISITOR,
	  0,		0, NULL },
	{ "memote",	f_emote,	L_VISITOR,
	  0,		1, "<text>" },
	{ "morelen",	f_morelen,	L_VISITOR,
	  0,		0, NULL },
	{ "motd",	f_motd,		L_VISITOR,
	  0,		0, NULL },
	{ "next",	f_read,		L_VISITOR,
	  0,		0, NULL },
	{ "nl",		f_nl,		L_VISITOR,
	  0,		0, NULL },
	{ "out",	f_out,		L_VISITOR,
	  0,		0, NULL },
	{ "quiet",	f_quiet,	L_VISITOR,
	  0,		1, "<command>" },
	{ "quit", 	f_quit, 	L_VISITOR,
	  0,		0, NULL },
	{ "Quit",	f_quit,		L_VISITOR,
	  0,		0, NULL },
	{ "read",	f_read,		L_VISITOR,
	  0,		1, "<note number>" },
	{ "remote",	f_tell,		L_VISITOR,
	  0,		2, "<user> <message>" },
	{ "reply",	f_reply,	L_VISITOR,
	  0,		0, NULL },
	{ "say",	f_say,		L_VISITOR,
	  0,		1, "<text>" },
	{ "screenwidth",f_screenwidth,	L_VISITOR,
	  0,		0, NULL },
	{ "su",		f_su,		L_VISITOR,
	  0,		1, "<user>" },
	{ "sysbug",	f_dolog,	L_VISITOR,
	  0,		0, NULL },
	{ "tell",	f_tell,		L_VISITOR,
	  0,		2, "<user> <message>" },
	{ "termtype",	f_termtype,	L_VISITOR,
	  0,		0, NULL },
	{ "to",		f_to,		L_VISITOR,
	  0,		2, "<user> <message>" },
	{ "tzadjust",	f_tzadjust,	L_VISITOR,
	  0,		0, NULL },
	{ "version",	f_version,	L_VISITOR,
	  0,		0, NULL },
	{ "who", 	f_who, 		L_VISITOR,
	  0,		0, NULL },
	{ "with",	f_with,		L_VISITOR,
	  0,		0, NULL },
	{ "write",	f_write,	L_VISITOR,
	  0,		0, NULL },
/* Resident commands */
	{ "afk",	f_afk,		L_RESIDENT,
	  0,		0, NULL },
	{ "alias",	f_alias,	L_RESIDENT,
	  0,		0, NULL },
	{ "beep",	f_beep,		L_RESIDENT,
	  0,		1, "<user>" },
	{ "beeplogin",	f_beeplogin,	L_RESIDENT,
	  0,		0, NULL },
	{ "capname",	f_capname,	L_RESIDENT,
	  0,		1, "<new capitalisation>" },
#if defined(INETD_SUPPORT) || defined(CDUDP_SUPPORT) || defined(IMUD3_SUPPORT)
	{ "chanblock",	f_chanblock,	L_RESIDENT,
	  0,		0, NULL },
#endif
	{ "chex",	f_chex,		L_RESIDENT,
	  CMD_AUDIT,	2, "<old name> <new name>" },
#ifdef CDUDP_SUPPORT
	{ "chosts",	f_hosts,	L_RESIDENT,
	  0,		0, NULL },
#endif
	{ "desc",	f_desc,		L_RESIDENT,
	  CMD_AUDIT,	0, NULL },
	{ "earmuffs",	f_earmuffs,	L_RESIDENT,
	  0,		0, NULL },
	{ "edesc",	f_desc,		L_RESIDENT,
	  CMD_AUDIT,	0, NULL },
	{ "eject",	f_eject,	L_RESIDENT,
	  0,		1, "<user>" },
	{ "email",	f_email,	L_RESIDENT,
	  0,		0, NULL },
	{ "entermsg",	f_messages,	L_RESIDENT,
	  0,		0, NULL },
	{ "epost",	f_post,		L_RESIDENT,
	  CMD_AUDIT,	1, "<note number>" },
	{ "finger",	f_finger,	L_RESIDENT,
	  0,		1, "<user>" },
	{ "followup",	f_followup,	L_RESIDENT,
	  0,		1, "[-e] <note number>" },
	{ "from",	f_from,		L_RESIDENT,
	  0,		0, NULL },
	{ "galias",	f_alias,	L_RESIDENT,
	  0,		0, NULL },
	{ "grupe",	f_grupe,	L_RESIDENT,
	  0,		0, NULL },
	{ "Grupe",	f_grupe,	L_RESIDENT,
	  CMD_AUDIT,	0, NULL },
	{ "go",		f_go,		L_RESIDENT,
	  0,		1, "<room filename | exit>" },
	{ "home",	f_home,		L_RESIDENT,
	  0,		0, NULL },
#ifdef INETD_SUPPORT
	{ "hosts",	f_hosts,	L_RESIDENT,
	  0,		0, NULL },
	{ "ilocate",	f_ilocate,	L_RESIDENT,
	  0,		1, "<user>" },
	{ "import",	f_import,	L_RESIDENT,
	  0,		1, "<user>@<JeamLand Talker>" },
	{ "intercode",	f_ichannel,	L_RESIDENT,
	  0,		1, "[:]<message>" },
	{ "interjl",	f_ichannel_jl,	L_RESIDENT,
	  0,		1, "[:]<message>" },
	{ "intermud",	f_ichannel,	L_RESIDENT,
	  0,		1, "[:]<message>" },
#endif
#if defined(INETD_SUPPORT) || defined(CDUDP_SUPPORT)
	{ "iquery",	f_iquery,	L_RESIDENT,
	  0,		2, "<host> <item>" },
#endif
	{ "jobs",	f_jobs,		L_RESIDENT,
	  0,		0, NULL },
	{ "join",	f_join,		L_RESIDENT,
	  0,		1, "<user>" },
#ifdef INETD_SUPPORT
	{ "jlhosts",	f_hosts,	L_RESIDENT,
	  0,		0, NULL },
#endif
	{ "kill",	f_kill,		L_RESIDENT,
	  0,		1, "[%]<job id>" },
	{ "last",	f_last,		L_RESIDENT,
	  0,	 	1, "<user | grupe>" },
	{ "leavemsg",	f_messages,	L_RESIDENT,
	  0,		0, NULL },
	{ "link",	f_link,		L_RESIDENT,
	  CMD_AUDIT,	2, "<direction> <fname>" },
	{ "lock",	f_lock,		L_RESIDENT,
	  CMD_AUDIT,	0, NULL },
#ifdef INETD_SUPPORT
	{ "lookup",	f_lookup,	L_RESIDENT,
	  0,		1, "<word>" },
#endif
	{ "mail",	f_mail,		L_RESIDENT,
	  0,		0, NULL },
	{ "mailnote",	f_mailnote,	L_RESIDENT,
	  0,		1, "<note number>" },
	{ "man",	f_man,		L_RESIDENT,
	  0,		0, NULL },
	{ "myrooms",	f_myrooms,	L_RESIDENT,
	  0,		0, NULL },
	{ "name",	f_name,		L_RESIDENT,
	  CMD_AUDIT,	1, "<room name>" },
	{ "nosnoop",	f_nosnoop,	L_RESIDENT,
	  0,		0, NULL },
	{ "passwd", 	f_passwd, 	L_RESIDENT,
	  0,		0, NULL },
	{ "paste",	f_paste,	L_RESIDENT,
	  0,		0, NULL },
	{ "plan",	f_plan,		L_RESIDENT,
	  0,		0, NULL },
	{ "post",	f_post,		L_RESIDENT,
	  CMD_AUDIT,	1, "<subject>" },
	{ "prompt",	f_prompt,	L_RESIDENT,
	  0,		0, NULL },
	{ "quotechar",	f_quotechar,	L_RESIDENT,
	 0,		0, NULL },
	{ "ralias",	f_alias,	L_RESIDENT,
	  0,		0, NULL },
	{ "remove",	f_remove,	L_RESIDENT,
	  CMD_AUDIT,	1, "<note number>" },
	{ "save", 	f_save, 	L_RESIDENT,
	  0,		0, NULL },
	{ "sched",	f_sched,	L_RESIDENT,
	  0,		2, "[-q] <delay> <command>" },
	{ "sendme",	f_sendme,	L_RESIDENT,
	  CMD_AUDIT,	0, NULL },
	{ "shout",	f_shout,	L_RESIDENT,
	  0,		1, "<message>" },
	{ "sig",	f_sig,		L_RESIDENT,
	  0,		0, NULL },
	{ "start",	f_start,	L_RESIDENT,
	  0,		0, NULL },
	{ "sticky",	f_sticky,	L_RESIDENT,
	  0,		0, NULL },
	{ "sudo",	f_sudo,		L_RESIDENT,
	  0,		0, NULL },
	{ "SUICIDE",	f_suicide,	L_RESIDENT,
	  0,		0, NULL },
	{ "swho",	f_swho,		L_RESIDENT,
	  0,		1, "<grupe>[,<grupe>, ..]" },
	{ "title",	f_title,	L_RESIDENT,
	  0,		1, "<new title>" },
	{ "unlink",	f_unlink,	L_RESIDENT,
	  CMD_AUDIT,	1, "<exit>" },
	{ "unlock",	f_unlock,	L_RESIDENT,
	  CMD_AUDIT,	0, NULL },
	{ "url",	f_url,		L_RESIDENT,
	  0,		0, NULL },
	{ "which",	f_which,	L_RESIDENT,
	  0,		1, "<command>" },
	{ "whisper",	f_whisper,	L_RESIDENT,
	  0,		2, "<user> <message>" },
#ifdef IMUD3_SUPPORT
	{ "3channel",	f_3channel,	L_RESIDENT,
	  0,		2, "<channel> <message>" }, 
	{ "3hosts",	f_3hosts,	L_RESIDENT,
	  0,		0, NULL },
#endif
/* Citizen commands */
#ifndef REQUIRE_REGISTRATION
	{ "validate", 	f_validate, 	L_CITIZEN,
	  0,		1, "<user>" },
#endif
	{ "warn",	f_warn,		L_CITIZEN,
	  0,		2, "<user> <warning>" },
/* Warden commands */
	{ "banish",	f_banish,	L_WARDEN,
	  0,		1, "<name>" },
	{ "boot",	f_boot,		L_WARDEN,
	  0,		2, "<user> <reason> [banish time]" },
	{ "cat",	f_cat,		L_WARDEN,
	  0,		1, "<file>" },
#if defined(CDUDP_SUPPORT)
	{ "creator",	f_cdudpchan,	L_WARDEN,
	  0,		1, "[:]<message>" },
#endif
	{ "curse",	f_curse,	L_WARDEN,
	  0,		2, "<user> <reason>" },
#ifdef INETD_SUPPORT
	{ "d-chat",	f_ichannel,	L_WARDEN,
	  0,		1, "[:]<message>" },
#endif
	{ "dump",	f_dump,		L_WARDEN,
	  0,		0, NULL },
	{ "echo",	f_echo,		L_WARDEN,
	  0,		1, "<message>" },
	{ "ed",		f_ed,		L_WARDEN,
	  CMD_AUDIT,	1, "<file>" },
	{ "grep",	f_grep,		L_WARDEN,
	  0,		2, "[-i] <substring> <file>" },
	{ "hash",	f_hash,		L_WARDEN,
	  0,		0, NULL },
#if defined(INETD_SUPPORT) || defined(CDUDP_SUPPORT)
	{ "iping",	f_iping,	L_WARDEN,
	  0,		1, "<host>" },
#endif
	{ "log",	f_log,		L_WARDEN,
	  0,		0, NULL },
	{ "ls",		f_ls,		L_WARDEN,
	  0,		0, NULL },
	{ "mbs",	f_mbs,		L_WARDEN,
	  0,		0, NULL },
	{ "meminfo",	f_meminfo,	L_WARDEN,
	  0,		0, NULL },
	{ "more",	f_cat,		L_WARDEN,
	  0,		1, "<file>" },
	{ "nbeep",	f_nbeep,	L_WARDEN,
	  0,		1, "<user> [reason]" },
	{ "netstat",	f_netstat,	L_WARDEN,
	  0,		0, NULL },
	{ "objects",	f_objects,	L_WARDEN,
	  0,		0, NULL },
	{ "people",	f_people,	L_WARDEN,
	  0,		0, NULL },
	{ "rm",		f_rm,		L_WARDEN,
	  CMD_AUDIT,	1, "<filename>" },
	{ "rooms",	f_rooms,	L_WARDEN,
	  0,		0, NULL },
#ifdef RUSAGE
	{ "rusage",	f_rusage,	L_WARDEN,
	  0,		0, NULL },
#endif
	{ "shutdown",	f_shutdown,	L_WARDEN,
	  0,		1, "<now | abort | delay> [reason]" },
	{ "snoop",	f_snoop,	L_WARDEN,
	  0,		0, NULL },
#ifdef STRBUF_STATS
	{ "strbufs",	f_strbufs,	L_WARDEN,
	  0,		0, NULL },
#endif
	{ "tail",	f_cat,		L_WARDEN,
	  0,		1, "<file>" },
	{ "uncurse",	f_curse,	L_WARDEN,
	  0,		1, "<user>" },
	{ "usercount",	f_usercount,	L_WARDEN,
	  0,		0, NULL },
	{ "warden",	f_channel,	L_WARDEN,
	  0,		1, "[:]<message>" },
	{ "watch",	f_watch,	L_WARDEN,
	  0,		0, NULL },
/* Consul commands */
	{ "as",		f_as,		L_CONSUL,
	  0,		2, "<level> <action>" },
	{ "at",		f_at,		L_CONSUL,
	  0,		2, "<user> <action>" },
	{ "board",	f_board,	L_CONSUL,
	  CMD_AUDIT,	1, "<board command; see help page>" },
	{ "chgender",	f_chgender,	L_CONSUL,
	  CMD_AUDIT,	0, NULL },
	{ "chlev",	f_chlev,	L_CONSUL,
	  CMD_AUDIT,	2, "<user> <new level>" },
	{ "chlim",	f_chlim,	L_CONSUL,
	  CMD_AUDIT,	3, "<user> <limit> <new limit>" },
	{ "chown",	f_chown,	L_CONSUL,
	  CMD_AUDIT,	1, "<user>" },
	{ "chpasswd",	f_chpasswd,	L_CONSUL,
	  CMD_AUDIT,	1, "<user>" },
	{ "consul",	f_channel,	L_CONSUL,
	  0,		1, "[:]<message>" },
	{ "cpnote",	f_cpnote,	L_CONSUL,
	  CMD_AUDIT,	3, "<note> <from room> <to room>" },
	{ "cproom",	f_cproom,	L_CONSUL,
	  CMD_AUDIT,	2, "<old filename> <new filename>" },
	{ "destroy",	f_destroy,	L_CONSUL,
	  CMD_AUDIT,	1, "<room filename>" },
	{ "rmroom",	f_rmroom,	L_CONSUL,
	  CMD_AUDIT,	1, "<room filename>" },
	{ "echoall",	f_echoall,	L_CONSUL,
	  0,		1, "<message>" },
	{ "echoto",	f_echoto,	L_CONSUL,
	  0,		2, "<user> <message>" },
	{ "events",	f_events,	L_CONSUL,
	  0,		0, NULL },
	{ "force",	f_force,	L_CONSUL,
	  0,		2, "<user> <action>" },
	{ "in",		f_at,		L_CONSUL,
	  0,		2, "<room> <command>" },
	{ "invis",	f_invis,	L_CONSUL,
	  0,		0, NULL },
#ifdef INETD_SUPPORT
	/* Not really suitable for a 'talker' ;-).. these are the existing
	 * channels. Do not add any more or risk the wrath of the intermud
	 * community! */
	{ "interadmin",	f_ichannel,	L_CONSUL,
	  0,		1, "[:]<message>" },
	{ "interjladmin", f_ichannel_jl, L_CONSUL,
	  0,		1, "[:]<message>" },
	{ "intertest",	f_ichannel,	L_CONSUL,
	  0,		1, "[:]<message>" },
#endif
	{ "iptab",	f_iptab,	L_CONSUL,
	  0,		0, NULL },
	{ "jlm",	f_jlm,		L_CONSUL,
	  0,		0, NULL },
	{ "mkroom",	f_mkroom,	L_CONSUL,
	  CMD_AUDIT,	1, "<room filename>" },
#ifdef REMOTE_NOTIFY
	{ "rntab",	f_rntab,	L_CONSUL,
	  0,		0, NULL },
#endif
	{ "showtail",	f_showtail,	L_CONSUL,
	  CMD_AUDIT,	2, "<user> <file>" },
	{ "siteban",	f_siteban,	L_CONSUL,
	  0,		0, NULL },
	{ "slylogin",	f_slylogin,	L_CONSUL,
	  0,		0, NULL },
	{ "trans",	f_trans,	L_CONSUL,
	  0,		1, "<user>" },
	{ "unbanish",	f_unbanish,	L_CONSUL,
	  0,		1, "<name>" },
	{ "valemail",	f_valemail,	L_CONSUL,
	  0,		1, "<user>" },
	{ "vis",	f_vis, 		L_CONSUL,
	  0,		0, NULL },
	{ "wall",	f_wall,		L_CONSUL,
	  0,		1, "<message>" },
/* Overseer commands */
	{ "aliases",	f_alias,	L_OVERSEER,
	  0,		1, "<user>" },
	{ "barge",	f_go,		L_OVERSEER,
	  0,		1, "<room filename | exit>" },
	{ "chemail",	f_chemail,	L_OVERSEER,
	  CMD_AUDIT,	2, "<user> <new email> | <-r> <user>" },
	{ "chtitle",	f_chtitle,	L_OVERSEER,
	  CMD_AUDIT,	2, "<user> <new title>" },
	{ "comment",	f_comment,	L_OVERSEER,
	  CMD_AUDIT,	1, "<user> [new comment]" },
	{ "cost",	f_cost,		L_OVERSEER,
	  0,		1, "<command>" },
	{ "cpuser",	f_cpuser,	L_OVERSEER,
	  0,		2, "<old name> <new name>" },
	{ "crash",	f_crash,	L_OVERSEER,
	  0,		0, NULL },
#ifdef JL_CRON
	{ "cron",	f_cron,		L_OVERSEER,
	  0,		0, NULL },
#endif
#ifdef DEBUG_MALLOC
	{ "dm",		f_dm,		L_OVERSEER,
	  CMD_AUDIT,	0, NULL },
#endif
	{ "rmuser",	f_rmuser,	L_OVERSEER,
	  CMD_AUDIT,	1, "<user>" },
	{ "erqd",	f_erqd,		L_OVERSEER,
	  CMD_AUDIT,	1, "<erqd command; see help page>" },
	{ "forceall",	f_forceall,	L_OVERSEER,
	  0,		1, "<command>" },
	{ "fpc",	f_fpc,		L_OVERSEER,
	  0,		1, "<user>" },
#ifdef IMUD3_SUPPORT
	{ "i3ctl",	f_i3ctl,	L_OVERSEER,
	  CMD_AUDIT,	1, "<action> ..." },
#endif
	{ "killpp",	f_killpp,	L_OVERSEER,
	  CMD_AUDIT,	0, NULL },
	{ "mkuser",	f_mkuser,	L_OVERSEER,
	  CMD_AUDIT,	1, "<username>" },
	{ "noidle",	f_noidle,	L_OVERSEER,
	  CMD_AUDIT,	1, "<username>" },
	{ "nopurge",	f_nopurge,	L_OVERSEER,
	  CMD_AUDIT,	1, "<user>" },
	{ "overseer",	f_channel,	L_OVERSEER,
	  0,		1, "[:]<message>" },
#ifdef PROFILING
	{ "profile",	f_profile,	L_OVERSEER,
	  0,		0, NULL },
#endif
	{ "purge",	f_purge,	L_OVERSEER,
	  CMD_AUDIT,	0, NULL },
	{ "reident",	f_reident,	L_OVERSEER,
	  0,		1, "<user>" },
	{ "reload",	f_reload,	L_OVERSEER,
	  CMD_AUDIT,	1, "<room filename>" },
#if defined(INETD_SUPPORT) || defined(CDUDP_SUPPORT)
	{ "rmhost",	f_rmhost,	L_OVERSEER,
	  CMD_AUDIT,	1, "[%]<host name>" },
#endif
	{ "sneak",	f_go,		L_OVERSEER,
	  0,		1, "<room filename | exit>" },
	{ "sreboot",	f_sreboot,	L_OVERSEER,
	  CMD_AUDIT,	0, NULL },
	{ "supersnoop",	f_supersnoop,	L_OVERSEER,
	  CMD_AUDIT,	1, "[-r] <user>" },
#if 1
	{ "test",	f_test,		L_OVERSEER,
	  0,		0, NULL },
#endif
	{ NULL, 	NULL, 		0,
	  0,		0, NULL },
	};
/* CT */

